#!/bin/bash
#PBS -N test_pbs
#PBS -l nodes=node16
#PBS -q qprodu
##PBS -l walltime=25:00:00
#PBS -j oe
#PBS -o out_^array_index^
#PBS -e err_^array_index^
#PBS -J 1-2
#PBS -V

cd $PBS_O_WORKDIR
hostname
cat $PBS_NODEFILE

/usr/local/MATLAB/R2024b/bin/matlab -nodisplay -r "disp('cdscdas')"
#/store/projects/HCP-preprocessed-resting-symmetry/scripts/resting_2.0_custom/preprocessing/start_preprocessing_resting_hcp.sh
#/usr/local/MATLAB/R2024/bin/matlab -nodisplay -nosplash -nodesktop -r "try, my_script('"test"'), catch e, disp(getReport(e)), exit(1), end, exit(0);"